---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-router
  namespace: default
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  # cert.gardener.cloud/purpose: managed
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - "a02beb55a6d4949e28556c0234df4f1c-1908183393.eu-central-1.elb.amazonaws.com"
    # secretName: secret-tls
  rules:
    - host: 'a02beb55a6d4949e28556c0234df4f1c-1908183393.eu-central-1.elb.amazonaws.com'
      http:
        paths:
          - path: /my-app/
            pathType: Prefix
            backend:
              service:
                name: my-app
                port:
                  number: 1336
