---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-router
  namespace: default
  annotations:
  # cert.gardener.cloud/purpose: managed
spec:
  tls:
    - hosts:
      - "xx0luvu5ep.flight.shoot.canary.k8s-hana.ondemand.com"
      - "*.ingress.xx0luvu5ep.flight.shoot.canary.k8s-hana.ondemand.com"
    # secretName: secret-tls
  rules:
    - host: 'my-app.ingress.xx0luvu5ep.flight.shoot.canary.k8s-hana.ondemand.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app
                port:
                  number: 1336