---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-router
  namespace: default
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  # cert.gardener.cloud/purpose: managed
spec:
  controller: k8s.io/ingress-nginx
  tls:
    - hosts:
      - "qo405mn370.flight.shoot.canary.k8s-hana.ondemand.com"
      - "*.ingress.qo405mn370.flight.shoot.canary.k8s-hana.ondemand.com"
    # secretName: secret-tls
  rules:
    - host: 'my-app.ingress.qo405mn370.flight.shoot.canary.k8s-hana.ondemand.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app
                port:
                  number: 1336
